import "dotenv/config";
import bcrypt from "bcrypt";
import { PrismaClient, ActionType } from "../generated/prisma/client.js";
import { PrismaPg } from "@prisma/adapter-pg";

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error("DATABASE_URL is not set");
}

const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

async function main() {
	const passwordHash = await bcrypt.hash("password123", 10);
  console.log('Starting database seed...');

  await prisma.activityLog.deleteMany();
  await prisma.shift.deleteMany();
  await prisma.employee.deleteMany();
  await prisma.user.deleteMany();

  const cafe = await prisma.user.create({
    data: {
      username: 'admin_demo',
      passwordHash: passwordHash, 
      BusinessName: 'The Daily Grind Cafe',
    },
  });

  console.log('Created Cafe Profile');

  const employees = await Promise.all([
    prisma.employee.create({ data: { userId: cafe.id, name: 'Alice (Senior)', role: 'Head Barista', hourlyWage: 25.0 } }),
    prisma.employee.create({ data: { userId: cafe.id, name: 'Bob (Junior)', role: 'Barista', hourlyWage: 15.0 } }),
    prisma.employee.create({ data: { userId: cafe.id, name: 'Charlie', role: 'Cashier', hourlyWage: 12.0 } }),
  ]);

  const [alice, bob, charlie] = employees;
  console.log('Created Employees');

  // 4. Create Shifts (Mixing Unoptimized and Optimized)
  // Let's assume today is a Tuesday.
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const shift1Start = new Date(today); shift1Start.setHours(8, 0, 0, 0);
  const shift1End = new Date(today); shift1End.setHours(14, 0, 0, 0);

  const shift2Start = new Date(today); shift2Start.setHours(12, 0, 0, 0);
  const shift2End = new Date(today); shift2End.setHours(18, 0, 0, 0);

  await prisma.shift.createMany({
    data: [
      // Unoptimized shift (e.g., someone manually scheduled Bob for too long)
      { employeeId: bob.id, startTime: shift1Start, endTime: shift2End, isOptimised: false },
      
      // Optimized shifts generated by your awesome algorithm
      { employeeId: alice.id, startTime: shift1Start, endTime: shift1End, isOptimised: true },
      { employeeId: charlie.id, startTime: shift2Start, endTime: shift2End, isOptimised: true },
    ],
  });

  console.log('Created Shifts');

  // 5. Create Activity Logs for the Dashboard UI
  await prisma.activityLog.createMany({
    data: [
      {
        userId: cafe.id,
        actionType: ActionType.HIRED_EMPLOYEE,
        metadata: { employeeName: 'Charlie', role: 'Cashier' },
        createdAt: new Date(today)
      },
      {
        userId: cafe.id,
        actionType: ActionType.RAM_OPTIMISATION,
        metadata: { 
          moneySaved: 125.50, 
          oldCost: 450.00,
          newCost: 324.50,
          hoursOptimized: 14,
          message: "Saved RM 125.50 on Tuesday schedule."
        },
				createdAt: new Date(today)
      },
    ],
  });

  console.log('Created Activity Logs');
  console.log('Seeding finished successfully!');
}

main()
  .catch((e) => {
    console.error('Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });